name: Test WorkFlow

on:
  push:
    branches: [ "main" ]

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Message to Console
      run: echo "Hello from the Ubuntu machine!"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x scripts/days.sh

    - name: Run shell script
      run: ./scripts/days.sh